### ISSUE TITLE
Category is slightly cut-off at the bottom

### ISSUE THREAD

**Issue by Paragoumba** [Seldszar/Gumbo#102]
**Describe the bug**
For some categories, the letters that for far below the font baseline (like 'g') are not drawn entirely.

**To Reproduce**
1. Follow a Just chatting online channel
2. Click on the extension's icon
3. The 'g' of the Just chatting category should be cut-off at the bottom

**Expected behavior**
The category name should be drawn entirely.

**Screenshots**
![image](https://user-images.githubusercontent.com/22895992/187989503-c076937e-1f71-4f04-a8d2-8fb3334f7e4a.png)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser Firefox Developer Edition
 - Version 105

**Comment by Paragoumba** [comment]
The line height seems to be the culprit as it's value is 1.25 which is not enough. Setting it to 1.3 fixes the problem. I would be glad to make a PR but didn't find the line defining it.

**Comment by Seldszar** [comment]
Thanks for the report, a fix has been pushed and will be published soon.
