### ISSUE TITLE
Feature request: category filters

### ISSUE THREAD

**Issue by Timsonrobl** [Seldszar/Gumbo#106]
Currently, users can filter notifications by channel name.
It would be great to have the ability to filter both notifications and broadcast lists by category/game. Very helpful if you are subscribed to a lot of variety-style streamers and never want to see specific games or categories of content.

**Comment by Seldszar** [comment]
A new settings section at the bottom of "Notifications" will be added in the next release (1.16). With that, you'll be able to add terms so notifications with categories containing one of them will be ignored.
