### ISSUE TITLE
Import settings won't open a finder window on MacOS using firefox

### ISSUE THREAD

**Issue by GettCouped** [Seldszar/Gumbo#107]
Hello,

I recently switched to Firefox and I'm trying to import Gumbo settings from the other browser and the import button isn't working.  The export button works fine.  I tried creating another profile in Firefox just in case it was a profile issue, but it doesn't work.  I have an M1 MBP on the latest version of MacOS (12.6). 

Let me know if there is anything you'd like me to do to diagnose.

**Comment by Seldszar** [comment]
Thanks for the report, a fix has been committed (https://github.com/Seldszar/Gumbo/commit/b39cc3fc0b14b7ef07878c432011642897f44ca4) & an update (1.15.3) will be published soon. Because it's a Firefox-specific issue, the new update should be released in the next minutes/hour.
