### ISSUE TITLE
opening link in new window? [Reopened]

### ISSUE THREAD

**Issue by 000744210** [Seldszar/Gumbo#123]
This is a reopen of a mis-documented bug report with more relevant information
 https://github.com/Seldszar/Gumbo/issues/122 

**Describe the bug**
The notification for category changed and gone live will open in a new window instead of a new tab.
The settings are configured to open in a new tab but it will only open in a new window.
![image](https://user-images.githubusercontent.com/63418620/209753220-7f845446-d366-406c-92bc-eea3470a2312.png)

**To Reproduce**
1. Wait for a streamer to go live or change category.
2. Click the notification
3. notice it opens in a new window.

**Expected behavior**
When the settings is configured for a new tab, it should open in a new tab.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 108
 
**Additional context**
This issue is fairly new with one of the more recent updates.
I have not tested on chromium browsers.

**Comment by Seldszar** [comment]
Thanks for the detailed report. I found the culprit (https://github.com/Seldszar/Gumbo/commit/7cf59a0688ae0625271806c4484c9164e9147e87) which was a side-effect from another previous fix (https://github.com/Seldszar/Gumbo/commit/ff82f7180c1882dc0fcafd44b53e9da10605534d).
I released a new version (1.16.4) which should be available on Firefox soon, and later on Chrome.
