### ISSUE TITLE
Number of Live Streams Online value not accurate in extension bubble || Streams not always refreshing properly/automatically

### ISSUE THREAD

**Issue by ScorelessPine** [Seldszar/Gumbo#129]
**Describe the bug**
1: "Number of Live Channels" number bubble on extension icon is no longer updating, not accurate to the current number of streams.
2: First set of streams shown when clicking the extension icon is not accurate, it shows previously-live streams from the last time you opened it instead. This does not update if you click refresh, only if you refresh the streams, and then close and reopen the mini extension window.

**To Reproduce**
Not applicable: constant issue, see above.

**Expected behavior**
I expect the current streams and number of live channels to be accurate to the real number.

**Screenshots**
![image](https://user-images.githubusercontent.com/28274052/225773141-b4dec05b-fb20-4eee-8aff-2e006f186fcd.png)
You can see that the number of followed streams in the shown list is much more than 5, which is what is shown in the extension bubble.

For the second issue, it happens after the previous list of channels stop going live, so it would take a few hours to get a good screenshot. The list of currently-live streams will show all of the streams that were live the last time you refreshed, however if they've gone offline, there will be no preview image for any of them, and the counter for their current stream length will show a time as if they had never gone offline.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Browser Version 110.0.5481.104
 - Extension Version 1.16.5

**Additional context**
This issue used to occur for me for a while, then for whatever reason stopped happening for about a month, right about when I was thinking of reporting the issue, however it has started happening again recently. I suspect these two issues are related, which is why they are in a single bug report. I do plan on updating my chrome version (it is slightly out of date and requesting me to update it), however I expect that this will not affect the issue. If it does somehow solve it, I will come back and update this in another comment, however assume that it won't in the meantime.

**Comment by Seldszar** [comment]
From what it seems, this is most likely due to the service worker randomly breaking.

This is unfortunately something I can't fix on my end and it's been like that for years now (https://bugs.chromium.org/p/chromium/issues/detail?id=1271154).

**Comment by BrianJ20** [comment]
I have the same issue and have had it since I started using Gumbo.  But it goes away after closing chrome all the way down and restarting.  And it comes back every time my computer comes out of the hibernate state.

So basically every day I turn the computer on, restart chrome from scratch, and Gumbo works the entire day until next morning.

**Comment by Seldszar** [comment]
So, after digging the Chromium's issue tracker, I found a solution to automatically reload the extension when the service worker stops responding. It's not a perfect solution, but it seems to significantly reduce the issue.

A new version will be available soon and I hope this ugly workaround will help everyone (and finally give me some peace). I'll close this issue when it'll be published on the all stores.
