### ISSUE TITLE
Chrome turning off the extension due to excess reloading

### ISSUE THREAD

**Issue by Zarradhoustra** [Seldszar/Gumbo#133]
**Describe the bug**
Chrome is deactivating due to excessive reloading since last patch. Several reports about this since latest update. Right before the crash, the icon start flashing rapidly:

![image](https://user-images.githubusercontent.com/6427520/227800734-b6d7d4db-d214-4c60-8ca6-73b2b6fee85e.png)

**Comment by Seldszar** [comment]
I'm sorry about this issue, I'll do my best to release a fix as soon as possible.

**Comment by Seldszar** [comment]
So, I'll remove the workaround for the time being (https://github.com/Seldszar/Gumbo/commit/6f00bd2fae5ee32731cfa885740941c58a3cedd7).

My intention was to prevent the extension from hanging from time to time (which is annoying, I know), but if this workaround causes this kind of problem, it's not something I'll tolerate. Maybe my implementation was wrong, but I'll have to do more research (or ignore the original problem) beforehand.

As a reminder, this is something the Chrome team has been aware of for about 2 years and the only tangible solution would be to allow Manifest V2 browser extensions back into their Web Store.

**Comment by Zarradhoustra** [comment]
No worries it happens to the best of us. There are a few different implementations of that workaround in the chromium issue you linked but imho the dirty workaround you can do is to refresh the icon every 5 or 10 mins but I think it would best is to just wait for chromium to fix the issue as it is very well documented already. Cheers
