### ISSUE TITLE
Gumbo icon doesn't refresh

### ISSUE THREAD

**Issue by SiempreGaga** [Seldszar/Gumbo#135]
**Describe the bug**

After a while, numbers will stop showing here in **_1_**, and number won't change even if someone goes on stream, and notification won't be received
Refreshing manually with **_2_** works though.

**Expected behavior**
Refresh should happen automatically, as before

**Screenshots**
[https://i.imgur.com/LnMRgte.png]

**Desktop (please complete the following information):**
 - W10
 - Firefox
 - Version 111.0.1 (64 bits)

**Comment by MardeK21** [comment]
I have the same bug too. But since yesterday it seems the Gumbo icon is working and shows me the right number of streams online.

However, I still don't receive notifications when a stream goes online
