### ISSUE TITLE
Allow The Popup Window To Be Expanded

### ISSUE THREAD

**Issue by enthusiast01** [Seldszar/Gumbo#141]
Please allow the popup window when you click on the app to be expanded to be adjustable height (mouse drag to size). That will add more of a 1 click functionality so having to scroll down the list of live streams is minimized.

**Comment by Seldszar** [comment]
It's currently impossible to do what you're asking because the maximum height of an extension popup is 600px (https://developer.chrome.com/docs/extensions/reference/browserAction/#popup), which is the default height Gumbo is using.
