### ISSUE TITLE
[Feature Request] Follow windows light/dark theme

### ISSUE THREAD

**Issue by Tywele** [Seldszar/Gumbo#145]
**Is your feature request related to a problem? Please describe.**
I can only choose either light or dark theme.

**Describe the solution you'd like**
It would be nice to set the theme to automatic so that it follows with the Windows light/dark theme

**Comment by Seldszar** [comment]
A new version (1.17) has been submitted, adding a new "System" option to the theme setting which follows the browser's preferred color scheme. This version is now available on Mozilla and will be on Chrome in the coming days.
