### ISSUE TITLE
[Feature Request] Open stream in theater mode

### ISSUE THREAD

**Issue by Tywele** [Seldszar/Gumbo#146]
**Is your feature request related to a problem? Please describe.**
There is no setting to open a stream in theater mode automatically when clicking on it.

**Describe the solution you'd like**
Add a setting to set the behaviour to open a stream in theater mode automatically when clicking on it.

**Comment by Seldszar** [comment]
There is no way to do that without injecting a content script, and I don't intend to do that. If you want to automatically switch to theater mode, there are plenty of extensions that already do that, like BTTV or FFZ.

**Comment by Tywele** [comment]
Seems like I haven't looked into the BTTV settings for a long time and forgot that it had this settings thank you
