### ISSUE TITLE
Search for localized names in the search box

### ISSUE THREAD

**Issue by akawshi** [Seldszar/Gumbo#150]
**Is your feature request related to a problem? Please describe.**
It's not possible to search for localized names in the search box (although it seems to be possible to search for all character types in the title).    
  
**Describe the solution you'd like**
Search for localized names in the search box.  
  
**Describe alternatives you've considered**
You can search by user ID, but many Asian streamers have localized names in kanji, hangul, or kana. Usually, we remember them by their localized name, so it's a little inconvenient to only search by user ID.

**Comment by Seldszar** [comment]
Thanks for the feedback. I added the ability to search by display name in followed users/streams and top streams (https://github.com/Seldszar/Gumbo/commit/e74cabe2a41efddcefba3e0eda8f8f8de0790c06).

This update will be available as soon as possible on Firefox/Chrome stores.
