### ISSUE TITLE
Import Settings Disabled

### ISSUE THREAD

**Issue by mepherion** [Seldszar/Gumbo#161]
**Describe the bug**
The button to "Import Settings" is disabled

**To Reproduce**
1. Go to "Settings"
2. Click on "Advanced"

**Expected behavior**
"Import Settings" button is enabled and allows uploading the JSON file

**Screenshots**
![screenshot](https://github.com/Seldszar/Gumbo/assets/20154933/9c6f265f-4b4c-40ad-ad30-60712d285f85)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome v116.0.5845.96
 - Gumbo Version: v1.18.1

**Comment by Seldszar** [comment]
Sorry about that, a new version (1.18.2) has been submitted to solve this issue.
