### ISSUE TITLE
Add settings (size/color) for the streams title/description popup.

### ISSUE THREAD

**Issue by placchio** [Seldszar/Gumbo#166]
-Is your feature request related to a problem? Please describe.
The streams title/description popup is waaay too big and the bright purple is super flashy. 

-Describe the solution you'd like
Adding the possibility to change the size and the color of the popup. Kinda like the badge settings.

-Additional context
Most of the time the popup is sooo big that cover almost the entire preview of the stream above/below.

**Comment by placchio** [comment]
Hopefully you are planning to fix this eventually.
As a fast scroller, the popup being so huge gets always in the way and makes it difficult to see thumbnails and read titles faster.

**Comment by Seldszar** [comment]
The next release will update the tooltip style, looking like the following:

![](https://github.com/Seldszar/Gumbo/assets/3079214/62468dcc-250f-4661-9292-9d765b643242)
