### ISSUE TITLE
Add setting to overwrite extension language

### ISSUE THREAD

**Issue by chrisheib** [Seldszar/Gumbo#169]
Hey there, first of all thanks for this extension! 

I am using the extension in german Edge, and the german popups are... a bit weird. I would prefer to use the extension in english. 

Might be a good addition to the settings menu.

**Comment by chrisheib** [comment]
I took a pass over the german translation and fixed a bunch of stuff. 

This one was bugging me the most: 
![image](https://github.com/Seldszar/Gumbo/assets/6112968/33e09ead-6cea-4af9-9a41-31343e6272c6)

The german string was missing a space and the wording was absolutely butchered. 

If you include this translation update I guess I would be fine using the german version, as the translation is mostly fine in the other places. Bit unlucky that the maybe most important place is so messed up currently 😅

**Comment by Seldszar** [comment]
A new release (1.18.5) with the updated translations has been submitted and will be available soon.

**Comment by chrisheib** [comment]
Works like a charm, thanks a lot <3

**Comment by chrisheib** [comment]
I edited the translation from 'spielt jetzt' to 'streamt jetzt', as the first one ('now playing') isn't working great for categories like just chatting. Don't stress merging it in, the current one is already great super useful.
