### ISSUE TITLE
Generally buggy behavior in recent Chrome build?

### ISSUE THREAD

**Issue by jbjhjm** [Seldszar/Gumbo#175]
**Describe the bug**
Hi Seldszar, a few days ago a new Chrome version has been rolled out and since then I'm experiencing following issues:

- Gumbo does not refresh or show notifications, only updates when opening panel and hitting refresh manually
- Gumbo panel does not open when clicking the toolbar icon (unfortunately I could not find out when it's happening til now.)
- resetting/reinstalling Gumbo did not solve these issues
- same issue on my notebook + desktop, hinting at a more general issue

I think it happened at the same time Chrome introduced a new "RAM saving" feature.
In general it seems that it works by throttling/hibernating background tabs.
My guess is it affects workers / views of extensions as well.
The Chrome version is: 119.0.6045.124

I realize this is a rather vague bug report. 
I'm doing so in order to find out if others are experiencing the same.
Any feedback of you, as well as other users that can confirm or deny these issues, is appreciated.

**To Reproduce**
1. Install Chrome 119.0.6045.124
2. Install Gumbo
3. Authorize Gumbo
4. (... well, wait for anything to happen - didn't auto-refresh a single time over the recent days.)

In case it matters, running on Win 10 Pro 22H2

**Comment by Seldszar** [comment]
This is most likely an issue with the service worker becoming unresponsive. It's unfortunately an old browser issue, still discussed to this day, and there's not much I can do until they find a proper fix.
