### ISSUE TITLE
Offline streams are not removed from the list, refreshing extension does nothing

### ISSUE THREAD

**Issue by Ralkero** [Seldszar/Gumbo#177]
**Describe the bug**
When I open Gumbo, streams that are not currently live or that were recently live are still shown in the list. Refreshing the extension does not do anything. Removing and re-installing the extension fixes the problem temporarily, but it happens again as soon as a new stream is added to the list or when one goes offline. 

**To Reproduce**
1. Go to any webpage.
2. Click on Gumbo extension icon.
3. You will see streams that are not live in the list of live streams. 

**Expected behavior**
1. Click Gumbo icon.
2. Only streams which are currently live should appear. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Browser: Mozilla Firefox
 - Version: 122.0.1 (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by Konako1** [comment]
i have the same problem, but in my case new streams are not added to the list

![image](https://github.com/Seldszar/Gumbo/assets/79690555/515964a8-48f7-4edc-a904-48672be0844a)

**Comment by Seldszar** [comment]
This is most likely an issue with the service worker becoming unresponsive. It's unfortunately an old browser issue, still discussed to this day, and there's not much I can do until they find a proper fix.
