### ISSUE TITLE
Gumbo in Firefox doesn't display offline streams

### ISSUE THREAD

**Issue by ogdenwebb** [Seldszar/Gumbo#18]
**Describe the bug**

The extension doesn't display offline streams (no matter if "Show live channels only" in Settings is enabled or not).

**Desktop:**
 - Linux
 - Firefox 
 - 97.0.2

**Additional context**

But I can see my followed channels in Settings -> Notifications

**Comment by Seldszar** [comment]
This settings is only used on the channel search section and has been renamed accordingly. However, a new section named "Followed Users" will be available starting version 1.3, where you can see the users you're following and apply filters at your convenience.
