### ISSUE TITLE
No longer works on MS Edge 126.0.2592.113

### ISSUE THREAD

**Issue by Jswk1** [Seldszar/Gumbo#182]
Hello,

Pardon me ignoring the bug report template, I believe it will be cleaner if I write this straight.

Since the last weeks I am no longer able to login to the extension. It keeps saying "Login with Twitch" and when I do, i get redirected to the oauth page and I get succesful message that I was logged in, yet the extension remains without session.

1. 
![image](https://github.com/user-attachments/assets/fb66848f-0b97-4029-a980-618165798af9)

2. 
![image](https://github.com/user-attachments/assets/3c957477-5d73-4a8b-b75d-476d55cbd4bd)

(it tells me to login in polish)

I am using MS Edge browser version 126.0.2592.113 as of now. What is worth mentioning is that I have the strictest security settings enabled, but seems like they dont make a difference. 

I am not sure what might help with investigation, but this is what I have in the dev tools when i get redirected:

![image](https://github.com/user-attachments/assets/b21a5b50-613e-4705-8c74-ac15052c3a6d)

**Comment by Seldszar** [comment]
I am also on Edge so it shouldn't be a browser issue. My guess is that some of the extension's data currently stored is invalid, causing the popup to throw exceptions. Did you try to reset the extension (extension://aalmjfpohaedoddkobnibokclgeefamn/settings.html#/advanced) or reinstall the extension?

**Comment by Jswk1** [comment]
Well I was kind of surprised no one reported this so it is probably on my end as you said. I tried reinstalling but no success. Anyway I will try to solve it on my side, not to bother you here now that you confirm it works for you in Edge.

**Comment by Jswk1** [comment]
FYI @Seldszar removing this extension https://chromewebstore.google.com/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp solved the problem. Dunno why I havent tried that before. Thanks for your help anyway and sorry for redundant issue.

**Comment by Seldszar** [comment]
Thanks for finding the root cause and no problem about what you did, I'll investigate why this particular extension is causing issues.

**Comment by ghostwords** [comment]
Hi all!

If using Edge, you can work around the conflict by uninstalling Chrome Web Store's version of Privacy Badger and installing the [version from the Edge store](https://microsoftedge.microsoft.com/addons/detail/privacy-badger/mkejgcgkdlddbggjhhflekkondicpnop). The Edge store version is still on Manifest V2, and is not impacted by this MV3-only bug.

**Comment by ghostwords** [comment]
If not using Edge, could somebody check if moving the toggles for `id.twitch.tv` and `api.twitch.tv` to green in Privacy Badger's options works around the conflict? Thank you!

**Comment by ghostwords** [comment]
I just added `api.twitch.tv` to Privacy Badger's compatibility list of domains. This type of update takes up to 24 hours to reach all Privacy Badger installations.
