### ISSUE TITLE
Search funtion bug

### ISSUE THREAD

**Issue by Joyfulbeekeeper** [Seldszar/Gumbo#184]
**Describe the bug**
Search is not avalible in "Top Streams" and "Top categories" sections.
For example, I want to check Quake Live streams. How am I supposed to find the game by scrolling 30 min down without search funtion?

**Expected behavior**
It should work, fix it please

**Desktop (please complete the following information):**
Windows 10
Google Chrome
127

**Comment by Seldszar** [comment]
Search isn't available in these pages because it's not possible to do so via the public Twitch API. You'll have to go to the search tab in order to find what you want.
