### ISSUE TITLE
Tab for followed categories

### ISSUE THREAD

**Issue by tev-tev** [Seldszar/Gumbo#27]
I'd love to be able to view my followed categories in a separate tab akin to a combo of followed streams and top categories. It'd be great if it included total viewership in the category as well but I realize that might make it too cluttered

**Comment by Seldszar** [comment]
As much I'd love to implement these missing features, it's unfortunately impossible until Twitch eventually adds these endpoints/data.

Reference: https://dev.twitch.tv/docs/api/reference

**Comment by tev-tev** [comment]
Gotcha, I wasn't aware of that, thanks for the info. I'm really enjoying Gumbo, I appreciate the work you put into it!

**Comment by Seldszar** [comment]
While Twitch will probably never implement an endpoint for returning followed categories, and because you were actually talking about the recently implemented pinned categories, I'll close this issue.
