### ISSUE TITLE
Add Languages

### ISSUE THREAD

**Issue by OJambrina** [Seldszar/Gumbo#30]
Hello, I would like if its possible to add languages, I will contribute translating it to spanish

Regards

**Comment by Seldszar** [comment]
After months of struggling trying solutions, I found Weblate being a fitting solution. I added the Spanish language so you can start translating if you want.

Here is the link: https://hosted.weblate.org/projects/gumbo/extension/es/
I have applied for a Libre hosting plan and hope to be approved in the next few days.

If a language is not in the list, you can request the one you like from there so I can add it to the list.

**Comment by OJambrina** [comment]
Hello, I've translated most of the strings, I left some without translation
because I don't know where does that string go, so I can see it when
updated, and get the proper translation

Regards
