### ISSUE TITLE
Pinned followed users and pinned categories

### ISSUE THREAD

**Issue by SW1FT** [Seldszar/Gumbo#31]
Adding 2 more tabs to the side bar for "Pinned followed users" and "Pinned categories" respectively.

EDIT: Forgot to mention, there's no way to pin categories at the moment, so that would need to be added.

**Comment by tev-tev** [comment]
Just want to add that the ability to pin categories similarly to pinning followed streams would effectively cover the use case I had in mind for creating issue #27

**Comment by Seldszar** [comment]
An update has been published, adding the ability to pin categories. It'll be available with version 1.14.
