### ISSUE TITLE
Count badge color too dark

### ISSUE THREAD

**Issue by movedoa** [Seldszar/Gumbo#35]
**Is your feature request related to a problem? Please describe.**
Firefox.
The background color of the count badge should not be black, rather it should be a light grey to integrate better with the Firefox dark theme.

**Describe the solution you'd like**
Comparison to uBlock origin:

![grafik](https://user-images.githubusercontent.com/13309951/161706859-fa7c928e-bc05-4d16-bd22-76df29735401.png)

Not sure if this is a default color that can be read from Firefox but the uBlock origin color seems pretty good.

**Comment by placchio** [comment]
** This is how the Gumbo live count badge shows up in incognito today after the latest google chrome update **

![122](https://user-images.githubusercontent.com/83036039/170265098-277d73c5-0754-4c7d-8104-25bf41de3111.png)

I dont know whats happening, maybe chrome changed something, but now the count badge is literally not readable.

**Comment by Seldszar** [comment]
Looks like they changed the default badge's text color.
I'll push an update to fix the color whenever I can.

**Comment by placchio** [comment]
Thank you very much

**Comment by Seldszar** [comment]
The fix (https://github.com/Seldszar/Gumbo/commit/019f805ffba0edbafee11fcd44ca00551c9068b9) will be delivered with the next version (1.10) whenever Chrome Web Store let me publish the update.

**Comment by Seldszar** [comment]
It's either using whatever color the browser is using by default or going back to square one.
I'll leave this until Chromium fixes their mess, or provide a way to actually change the text color on MV3.

**Comment by PiotrTekieli** [comment]
I do prefer black personally, much more obvious what it wants to say and much more easily readable. When I noticed the red it felt like a bug

**Comment by Seldszar** [comment]
Perhaps on Firefox, but since Chrome 102, the text color suddenly became a dark grey, making it really hard to read.
And on the top of that, it's impossible to change this color because MV3 doesn't provide a way to change it.

I guess I can add a special case for specific browsers, but it'll only be yet another band-aid for fixing something I shouldn't think about.

**Comment by Seldszar** [comment]
I think this color might do the job for both browsers.
Thankfully, Firefox automatically choose the correct color based on the background color. Chromium should honestly steal this feature.

![image](https://user-images.githubusercontent.com/3079214/170824699-e40c69df-2439-4b2b-9812-54d437c40f33.png)

Let me know if that sounds good to you.

**Comment by Seldszar** [comment]
The next update (v1.10.1) will have the color displayed in the previous message, for the time being.

There's currently a pending publication on Chrome Web Store so I'll wait until it's done then I'll push everything.

Closing this issue.
