### ISSUE TITLE
stores.accessToken.onChange is being called every minute which is causing notifications to fail to be sent

### ISSUE THREAD

**Issue by 000744210** [Seldszar/Gumbo#46]
**Describe the bug**
Every time the accessToken.onChange event is called, the extension will call `refresh` with the `withNotifications` set to false which means it won't send a notification. This is fine but not if it gets called every minute which it seems to be doing. Every time this event gets triggered it calls this every time `stores.followedStreams.set(followedStreams);` in the `refresh` function which means it will prevent the difference comparison from noticing that a new stream went live.

I am uncertain if this problem is just limited to me. It is probably a Chromium only problem due to how the problem relates to service workers.

I've been debugging why a lot of people are going live but I'm only getting notified by a few of them. I've narrowed it down to this problem. One odd problem is that it only calls accessToken.onChange when I don't have the background page debug window open. I had to write a persistent logging function to discover this because service workers go to sleep when you close the debug page.

My quick solution to this problem was to remove `refresh(false, true)` in the event to prevent the spam to the twitch API and to fix the notification difference comparison problem it was causing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Google Chrome | 100.0.4896.127 (Official Build) (64-bit) (cohort: Stable)

**Comment by Seldszar** [comment]
Thanks for the report. Working with service workers can be confusing sometimes.

**Comment by 000744210** [comment]
No problem. I'm testing the new version now. I'll tell you if it got fixed.

**Comment by 000744210** [comment]
It seems to be fixed. It is no longer being spammed when the service worker goes to sleep.
