### ISSUE TITLE
Gumbo does not display the correct stream information.

### ISSUE THREAD

**Issue by Straga27** [Seldszar/Gumbo#49]
**Describe the bug**
Gumbo is displaying streams that are offline as online and is reporting a runtime of the stream into 60+ hours which is incorrect

**To Reproduce**
I'm logged into twitch via Gumbo and opening the extension and clicking on followed streams displays the wrong info.

**Expected behavior**
Opening the followed streams section should display the correct info

**Screenshots**
![image](https://user-images.githubusercontent.com/61248402/168038507-5fad56f3-9128-4dbd-8194-997963b224df.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser Firefox

**Smartphone (please complete the following information):**
 - Version 100.0

**Additional context**
I have logged out and re authenticated Gumbo numerous times to try and fix the problem to no avail.

**Comment by Seldszar** [comment]
- Is clicking the refresh button (the one on the right side of the search bar) does something, like an animation?
- Did you try re-installing the extension and/or update it?

**Comment by Straga27** [comment]
Yes and yes.

**Comment by Seldszar** [comment]
Can you go to this URL (`about:debugging#/runtime/this-firefox`), click the extension's "Inspect" button and see if there's any errors in the "Console" tab?

If there's no errors, while keeping the toolbox open, can you open the popup, click the refresh button then go to the "Network" tab and see if there's any requests? If that's the case, is there any requests with a status code other than 200?

**Comment by Seldszar** [comment]
Update about your situation, A new version (1.8.6) is going to be available with the addition of a "Reset Extension" button in **Settings** ("Advanced" section). I hope this last recourse will finally help.

**Comment by Straga27** [comment]
Apologies for not getting back to you. There are no errors in the console
tab, but in the network tab the three bugged channels in the extension show
up with a 302 status code.

[image: image.png]

For the record this is still happening for sure.

**Comment by Seldszar** [comment]
Sorry but the image you attached isn't viewable. Please upload this image somewhere  so I can take a look.

**Comment by Straga27** [comment]
My bad.
![image](https://user-images.githubusercontent.com/61248402/169651214-23a065ba-60ac-4559-9886-29c30dfe1970.png)
There you go.

**Comment by Seldszar** [comment]
It looks like the API responses have been wrongly cached. Can you, from the Toolbox, do and Ctrl+F5 in order to purge the request cache, then click on the refresh icon in the extension window (top-right icon)?

Hopefully it'll fetch the most recent data. However I don't know how this cache issue happened in the first place, but it doesn't seem to be something on my part because this cache behavior is being dictated by the API server itself. I'll see if I can do add a cache busting for this particular case.

**Comment by Straga27** [comment]
I took the nuclear option and just erased all of my cache data for the
browser. Uninstalled the extension and then reinstalled it. Fixed.

What was making me suspicious was that Gumbo was logged in automatically
when I was reinstalling the extension before I took out the entire cache.
This lead me to think I had some dodgy cache data from twitch that the
extension was falling over I suppose.

Thanks for the help! Your extension is great.

**Comment by Seldszar** [comment]
That's what I was thinking as well.

In case other users have this similar issue and for future ones, I changed the fetch mode (https://github.com/Seldszar/Gumbo/commit/3a57c823b8633431de4caeb883fc9f621fced06d) so every API request will skip the browser's cache.
