### ISSUE TITLE
Batch Together Large Numbers of Notifications on Startup

### ISSUE THREAD

**Issue by TheKins** [Seldszar/Gumbo#51]
**Is your feature request related to a problem? Please describe.**
When starting the browser for the first time after starting up my PC, Gumbo tries creating a notification for every online stream I'm following at that time, which Windows slowly goes through one-by-one. Which can take a while when it's 15+ notifications unless I intervene and manually clear them all in the Notifications Center.

**Describe the solution you'd like**
The (late, lamented) Twitch Now extension would handle this with a single "# streams online" notification upon having to report a large number of online streams at once.

**Comment by Seldszar** [comment]
I'll reopen this issue because it seems the initial change isn't effective. I initially wanted to not send notifications during startup but there's no easy ways to do what I wanted due to the way the background script is currently working.
