### ISSUE TITLE
Crush, because of the performance?

### ISSUE THREAD

**Issue by NSurtsev** [Seldszar/Gumbo#61]
**Describe the bug**
Sometimes, when I open extension, It crushes with
"Uh-oh, Gumbo is not responding anymore! Please use the button below to reload the extension."

**To Reproduce**
Press the extension button

**Expected behavior**
fast opening

**Desktop (please complete the following information):**
 - Windows 10 19044.1706
 - Google Chrome 102.0.5005.63

**Additional context**
Yes, my laptop is rather old (Inter Core i5-4200U with 16 GB RAM, Radeon HD 8670M with 1 GB dedicated VRAM, Samsung SATA SSD), but still extension needs some optimisations (it's much heavier than good old Twitch Now), it also happens on my Linux which is much faster.
One thing that already comes to mind as one of issues - we don't need to see "real-time tracking of seconds of all my 50 followed online streams", just do it like in Twitch Now - brief snapshot of online time until refreshing.

**Comment by Seldszar** [comment]
It's being caused by the background service worker randomly breaking, putting the extension in a limbo state. It's a known issue, which is unfortunately on the hands of the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1271154
