### ISSUE TITLE
Count badge color too bright

### ISSUE THREAD

**Issue by mryx007** [Seldszar/Gumbo#65]
Is your feature request related to a problem? Please describe.

Chrome, 
The background color of the count badge is too bright now. It was perfect before. I can barely see how many are online
![Unbenannt](https://user-images.githubusercontent.com/106607032/171199412-eb8e47d7-fde9-4d31-8782-7e4db7b1cca2.jpg)

**Comment by Seldszar** [comment]
I'll not be able to please everyone with this change, between Firefox with the misleading red background, pre and post Chrome 102, it's annoying to deal with these changes without having a real way to fix this issue once and for all.
I could add a way to select a color, but after that I'll abandon this crusade.
