### ISSUE TITLE
Make the category change notification display the category name in the body

### ISSUE THREAD

**Issue by peachyclem** [Seldszar/Gumbo#67]
**Is your feature request related to a problem? Please describe.**
Chrome displays the context message very tiny in the corner of the notification which is the main focus of a this notification.

**Describe the solution you'd like**
The body should display the main purpose of the category change notification which is the category name.

This is a screenshot from my version of the extension. 
![image](https://user-images.githubusercontent.com/83135767/171514597-e213a165-a37f-4402-8f94-91ca8a393d36.png)

**Comment by Seldszar** [comment]
The issue is usually streamers, when they change the category, they also change the title.

**Comment by peachyclem** [comment]
Is the title that important though?

**Comment by Seldszar** [comment]
It can be useful to some people wanting to know more, especially when it comes to speedrun. And with the current layout, the category is always at the same place.
