### ISSUE TITLE
Stuck loading forever

### ISSUE THREAD

**Issue by LordSimal** [Seldszar/Gumbo#70]
**Describe the bug**
I think since a few days ago the app is broken and stuck loading the channels like it is shown in the screenshot.

**To Reproduce**
1. Open the app

**Expected behavior**
Live twitch channels are shown

**Screenshots**
![image](https://user-images.githubusercontent.com/9105243/171843393-a0e8ad5a-7553-4073-8ef8-fc236f4881a1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version 102.0.5005.63
 - App Version 1.11.0

**Additional context**
When opening the chrome inspector for the app the error states:
```
popup.js:25 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'enabled')
    at y.yk [as constructor] (popup.js:25:41860)
    at y.V [as render] (popup.js:2:24064)
    at P (popup.js:2:21591)
    at popup.js:2:17544
    at Array.some (<anonymous>)
    at x (popup.js:2:17441)
```

Opening the related JS file and "pretifying" the Code it states this error:
![image](https://user-images.githubusercontent.com/9105243/171843740-ce01e418-e437-4096-a977-40618210d9c6.png)

**Comment by Seldszar** [comment]
Like I already answered this same question on Chrome Web Store, I may have messed up with the data migration with the last version. I have a couple of fixes ready for shipping but I'll have to wait until Chrome Web Store allows me to do so.

**Comment by Seldszar** [comment]
In the meantime, one of the options is to reset the extension and everything should be fixed.

However, due to an error with one of the migrations, the badge icon gets disabled and you'll have to manually enable it in the settings.

**Comment by LordSimal** [comment]
Sorry, didn't see the question in the Chrome Web Store. Indeed uninstallting and re-installing fixed the issue 👍🏻

**Comment by LordSimal** [comment]
I totally understand you. External dependencies which don't respond accordingly are pretty frustrating...
