### ISSUE TITLE
Sound only notifications & for individual channels

### ISSUE THREAD

**Issue by FabrizioMFE** [Seldszar/Gumbo#73]
**Is your feature request related to a problem? Please describe.**
I don't like desktop notifications ever because they disrupt either gameplay or work.

**Describe the solution you'd like**
I'd like for Gumbo to have a choice for sound only notifications like Twitch Now does.
![nYksTMHKlT](https://user-images.githubusercontent.com/13880444/172034494-11e677ed-affa-4aaa-b21c-598536984522.png)

**Describe alternatives you've considered**
Alternative would be to stick with Twitch Now when it's unknown when it will stop working completely or just look for a different extension.

**Additional context**
The only thing I want out of an extension like this is, being able to see currently live streams and get a **sound only** notification when a specific stream from my followed goes live, ideally with volume / sound selection, like exactly the same as Twitch Now would be fine.

Thank you! 🙌

**Comment by Seldszar** [comment]
https://github.com/Seldszar/Gumbo#are-sound-notifications-supported
