### ISSUE TITLE
Import settings file into Firefox version broken

### ISSUE THREAD

**Issue by vb4472** [Seldszar/Gumbo#78]
Version 1.11.3 of the extension has this problem (and probably earlier versions too but I only started using the extension yesterday).

* I first tried exporting settings from Chrome and then importing to Firefox. Didn't work.
* Then I tried making changes on the Firefox version, exporting settings, resetting extension, and then importing the file back into Firefox. Didn't work.

This only affects Firefox version. Chrome version imports all settings no problem.

**Comment by Seldszar** [comment]
Can you give more info about your browser?
No issues on Firefox 101.0 on my side.

**Comment by Seldszar** [comment]
So, resolving this issue might take a while.

One solution is to move the settings to a standard web page (https://bugzilla.mozilla.org/show_bug.cgi?id=1658694#c2).

Maybe other or (not too much) hacky solutions exist out there, I'll keep looking.

**Comment by Seldszar** [comment]
Version 1.13.0 makes it settings are now in a separate page so interactions causing focus loss, like file pickers, will not affect this page.
