### ISSUE TITLE
Ability to follow channels without Twitch account

### ISSUE THREAD

**Issue by panosalevropoulos** [Seldszar/Gumbo#84]
Right now, this add-on doesn't work without a Twitch account. Would it be possible to add a functionality to follow channels without actually having a Twitch account (e.g. by providing the channel's username)? The data could then also be exported/imported.

This is what [Twire](https://github.com/twireapp/Twire) does for example.

**Comment by Seldszar** [comment]
I have no plans for this option.

The current operation of the Helix API requires an authentication token to retrieve data. I could deploy a server delivering app tokens, but I see no benefit in offering this alternative just for a few people.
