### ISSUE TITLE
Gumbo doesnt update/refresh streams

### ISSUE THREAD

**Issue by placchio** [Seldszar/Gumbo#90]
(Chrome latest update, win 10)

Gumbo suddenly started not updating/refreshing streams, which makes the badge not updating, which means i miss  streams all the time this problem happens. I dont have a way to know if a stream is actually live or ended because gumbo can gets stuck for hours (or even forever if i dont "recognize" that its stuck). 
To unstuck it i have to disable/enable the extension, which sometimes fixes the issue sometimes doesnt. If it doesnt, i try to force the refresh via the refresh button, which again sometimes work and sometimes doesnt.

I already tried purging cache e reinstalling gumbo, but unfortunately the problem is still there. 
Actually, prior to the reinstall i could kinda guess gumbo wasnt refreshing because the streams that were there even after they ended didnt have the thumbnails ( #49 ) Now its worse because everything its completely freezed in time, with thumbnails and all, so if a stream ends or a new one starts i literally have no way to know unless i randomly restart gumbo or refresh.

I dont know if im the only one having these big issues, but hopefully there is a fix for this because i use this extension quite a lot but in this state is basically useless.

**Comment by BrianJ20** [comment]
I'm seeing the exact same thing.
Using Chrome Version 104.0.5112.81 (Official Build) (64-bit) and Gumbo 1.13.0

**Comment by Seldszar** [comment]
It could be either a bogus Twitch response causing the cache to be wrong indefinitely, or this damn service worker issue being unresolved since forever.

- For the first one, I pre-emptively pushed an update to force the browser not to cache any responses from the Twitch API.
- I can't do anything about the second option because it's up to Chromium team, not me.

**Comment by placchio** [comment]
@BrianJ20 Im curious: are you using the pixeltris vaft-script for ublock origin?

**Comment by BrianJ20** [comment]
> @BrianJ20 Im curious: are you using the pixeltris vaft-script for ublock origin?

I do use ublock origin, but not the script you mentioned.  Also have ublock disabled on the twitch domain.

**Comment by placchio** [comment]
> I do use ublock origin, but not the script you mentioned. Also have ublock disabled on the twitch domain.
So its not ublock or the script, atleast there is that.

**Comment by BrianJ20** [comment]
Chrome updated the addon to 1.14.0 today and so far everything has worked as it should.

**Comment by placchio** [comment]
Still bugged for me. 

Gumbo doesnt refresh when streams end and even if sometimes, without restarting the extension, i manage to get it to refresh (i "force" it by switching from followed tab to top streams, scroll down until it loads more streams, and then switch back to followed tab ) the badge doesnt update along and keeps being stuck at the previous number.
Also the enable/disable badge button is laggy and doesnt work most of the time (this also happened before the 1.14 update).

**Comment by 000744210** [comment]
Has this been resolved?

**Comment by placchio** [comment]
No, gumbo still bugs atleast twice a day for me.

FYI: i read a review on the chrome store of the other extension i mentioned in the comment above (the "Nowstreaming - twitch" one) that other people are also experiencing the update/refreshing problem for that too. 
So the issues are definitely not solved.

**Comment by placchio** [comment]
This bug is getting worse and worse. 
Today i already restarted Gumbo 5 times.. it basically doesnt auto-update/refresh anymore unless i disable/enable it everytime.
Its unusable.

**Comment by CatzHoekk** [comment]
For me it started to act like this sometime during the last week

**Comment by placchio** [comment]
Did twitch or chrome change something? 
Its about a week now that the bug seems it got fixed on its own.
I dont want to say its 100% fixed because i dont even know what happened in the first place, but i guess ill continue to check if the bug shows up again.
Maybe ill update in a month or something.

**Comment by baoc2** [comment]
Do you guys still have this issue?
Mine has it for months but most of the time I just ignore it.
But the refresh button won't even refresh the whole page instantly on my end bothers me the most.
The worst part is that I never know my favorite streamers got online until I occasionally manual refresh it, close the extension screen and open it again after a few second to know that they have been online for an hour...

**Comment by placchio** [comment]
Yes, unfortunately the issues you described are still there after months and are super annoying and frustating.

**Comment by herosolaire** [comment]
Well to bad, this issue makes Gumbo basically useless most of the time. Anyone knows any extension alternatives?

**Comment by Rifhifi** [comment]
It seems to be fixed with last version of Chrome (108.0.5359.124).
I don't have this issue anymore.
