### ISSUE TITLE
Content slightly cut off when used from firefox overflow menu

### ISSUE THREAD

**Issue by odinhb** [Seldszar/Gumbo#94]
**Describe the bug**
If you move the extension to the "overflow menu" in Firefox (so it isn't show all the time), the extension is opened with a thick bar at the top and in a slightly thinner box which cuts off some of the content on the right side (like the scrollbar and the icon next to viewer count).

**To Reproduce**
1. Install Firefox
2. Install Gumbo
3. (optional) Sign in to Twitch in the extension, makes the bug more noticeable
4. Right click Gumbo's icon > "Pin to Overflow Menu"
5. Open Gumbo from overflow menu
6. Bleed from your eyes

**Expected behavior**
Content is not cut off

**Screenshots explain this better than words**
![Screenshot_20220814_232753](https://user-images.githubusercontent.com/49036561/184555742-75a4db9f-1ddb-4c66-8185-714af3e33fe5.png)

**Desktop (please complete the following information):**

<details>
<summary>Firefox 101 on Fedora Linux 35</summary>

![Screenshot_20220814_232822](https://user-images.githubusercontent.com/49036561/184555754-d96f3900-a001-4eb4-9745-d0c28557d253.png)

</details>

**Comment by odinhb** [comment]
Tried to reproduce on updated firefox, got a different bug:
![Screenshot_20220814_234747](https://user-images.githubusercontent.com/49036561/184556148-6c461a06-b14a-4a0d-9626-11a4603818d7.png)

What it should look like:
![Screenshot_20220814_234709](https://user-images.githubusercontent.com/49036561/184556151-633d820e-9644-4883-8881-baeb6d793361.png)

Version: Firefox 103 on Ubuntu Linux
![Screenshot_20220814_234819](https://user-images.githubusercontent.com/49036561/184556155-e3d3988c-0f01-4b9f-8b75-b35b352c5a94.png)

**Comment by Seldszar** [comment]
This issue cannot be resolved on my side and should be resolved with Firefox 106 (Nightly).

I'll mark this issue as done because there's nothing I can do besides asking you to wait for Firefox 106, which is planned for October 18th, 2022.

---

Bugzilla Ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1783972
Release Calendar: https://wiki.mozilla.org/Release_Management/Calendar
